# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p', 'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'Checkmate' do
  use_frameworks! :linkage => :static

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

post_install do |installer|
  react_native_post_install(installer)

  node_binary = "/opt/homebrew/bin/node"

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 1) node 경로 고정 (Hermes/Codegen/오토링킹 스크립트 안정화)
      config.build_settings['NODE_BINARY'] = node_binary
      config.build_settings['PATH'] = "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

      # 2) Pods는 코드사인 절대 하지 않게 (glog resource fork 에러 방지)
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
    end
  end
end